### ISSUE TITLE
Route local network traffic to wireguard network in container

### ISSUE THREAD

**Issue by tvories** [cmulk/wireguard-docker#10]
I'm struggling to figure out how to route my local network traffic BACK through the wireguard connection to the external peer.  My peers connect great, they can access local resources.  However, I can't figure out how to route traffic BACK to the external peer through the docker container.  Is this possible?

**Comment by tvories** [comment]
[Here is a bad drawing of my issue](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#R7Vtbc6M2FP41nmkf7AFhsPOY2HG3M9ttumm726eMDDKowYgKObbz6yuBBMjCNllfZzd5iM1BHMQ537njjjOar36hMI1%2BIwGKO8AKVh1n3AHA7gOPfwjKuqAM%2B6AghBQHclFFeMSvSBItSV3gAGXaQkZIzHCqE32SJMhnGg1SSpb6shmJ9bumMEQG4dGHsUn9ggMWyadwrYr%2BAeEwUne2LXlmDtViScgiGJBljeTcd5wRJYQV3%2BarEYqF8JRciusmW86WG6MoYW0uWP71%2FPL89cvT9OF16fivsz8ef1937WHB5gXGC%2FnEcrdsrUQQUrJI5TJEGVo1CR5O1XLL3JhdPi7HCSJzxOiaL5GM%2BsAtLpEQ8SSHZSXvcklUk%2FVALYRSx2HJuhID%2FyIl8RapePulwoWSBEhwsTvO3TLCDD2m0Bdnl9wUOC1i81ienuE4HpGY0PxaJ3DRMOhzesYoeUa1M0MwdTyPn9kq77pcd6jUlPYFxTloEKcXMyEYwp%2BlLlfvvwVRJ7pZ7g5u%2BQIHpKvqJP8Wis9fE4ZoAsUGPiG2JPRZ8eX7LFgXCw3tcakyXUW6KhKSoA29SRKMcZjwQx%2BJm3OC0BHmDuNWnpjjIBC3acREhRrrJEqWbFzdooBpUY6i1SHgngoBjmsgoKa7zygjC%2BpzN%2F%2BDqQk4up4Glqko222wVXAyRV0%2BHJRCKMHbIBSnAb32zckc2H6pkAWLccKBqdIQAZwAZlGJIgXAj3CK4geSYYaJAOKUMEbmDQhlJG0Cct0YIpiK%2B89Xoci%2BenCZOT1GYZDzhvFThuhLftFGABqMB6PBiNNDsZhz3rCeb0e8szf4nFl3YL%2FuYJYWOpvhlVBXXcQpwQnL9%2BTeddxxk0LwPM8h85AlE1gbVPQxnod85zGeiv1nPkT8c0z8Z0R72UuoFt4RGiCpHiv%2FE3dHFHMxICr8E05Cuamjq0dlYrrl2bZpeW6D8vr2qXR3Y%2BgKBTw9l4eEsoiEAuj3FXXDd1drPhJhT7n8%2FkWMraWq4IIRXeVohdlXcXnPlUf%2F1M6MV5JzfrCuHTwoZWlhQ2z4G3TEHzqPifu9EoM0RDuDULPOKYohwy%2F65o4fUKzLqvBmWNNh7bC9Grmy6PqrYiwOClZubuQ5oWKWH63rR9eKCnAgKvJLbymF69oC6S0rzg%2BCUDkYGwz02G5v1Kwb6zc90lvX2469geBixxWey0c%2FAOJmevDIuBB9IU6eFyDRd6A8xHOvSTKWdzCKTIlBnjJQVbNMqSpXfmIRzoTf5RWN%2BJwuxFUkidd5C4MKFpFgG%2BRhRDL%2BuUX63D4tpohXXzKNsxoDYSwSmTvoP4e5vdbSi1n%2BtytQtUkTd%2FiTrRFMmKV9o2OgOHobsE3k2k7P0%2Fh27Z6rcyGzWcZtbtNlHgFi9kUDoa25UHenB23h3uyWnsxt6cm8S8Y3YFZMXzBF4QLSQJDT5EewygKfW62ya%2FXAYKibZf8wszy9zZkti%2FtV1bLgNcMU0fwhHzD%2FN4pFGWXoWlVoqkaoKb253NtbJbbQb36zW1XUCJgYFY6qTSLGRCP9VkgPTPwgsXqYo2CGueegPV8ErUkAGeQfgp6JvhpXWDe%2FdzdbZwyJJSIXAhOqhNK1wbCX8nKlTZ2yuxvgbgT0G8mhXlAC2cTWCkpFPL7F24aWv39f7J0pqzxMM2atX%2FfFZYv4%2B%2FfHe4yK%2B2NXT8Sv3hs7%2FUtanaVZ3WC32W0rGIvLdtSLF7BX90B7%2FaYqsJw9qKpuONiAzAmqtBYjvYYg3TbadvQ2nx%2Fj9AlS%2FsyTpPA6onkHJhPujpYwjp8s8MQj1Op4cdKQacPMZ9jQuxuequ%2FaNPM78yTB67s9oBdtrmOKZVCtivRR%2FolE02Lm%2Fj5OqKFo5zjh7NpTjC86IxONDqAh27sGZNvvk7L2s%2BEtnayL6s%2FMoM%2FvtW09kvWH1wDsFoPxd2DXQXRlwO5fAbCHZjpycw3YNjtd79jeiaPrwja4SGncOV6xKuG2f5B92U7%2FznfYyuaSGvX9%2FfDJUMtpO01CR5l8%2F6QtyN8WihtqSttrKCpP9nqaGh%2BfuQukGjqy4apaOuW5I8%2F%2F29qNSkqu%2Bw0QYJa7f1I4m%2BXz8QBljMeVoCOH4qgasdDaiCXF5pC8nLF%2FljP2nMFYTcQ%2F5KP2bZP1gIi3Ta2EiLaUMNwfYngOtpTTtTHdjdXXs2%2BJsQPH54qNmp2r4zM0js1k5opdxgWi6qFBdcubON5G6Nj8dUGxL3nVCdS%2Bey5fhespt8EG7%2BM3z3O%2FQ6fgbCnXKqfQt9QrTgeCousNDjd7MWgufzRVLK9%2Beubc%2Fw8%3D)

**Comment by cmulk** [comment]
I see what you mean. First I would use the flag to disable MASQUERADE NAT as this will cause you problems routing back.

I think you have the right idea, putting the static route on the internal network to provide the path back to the VPN network (that's what I would do). The next part is that you should use --network host to put the container in host networking mode, which will create the wireguard interface on the host machine itself. This will make that interface available to the internal network so that those machines can route back through it. You will also need to make sure ip forwarding is enabled on that host if not already, and appropriate  firewall rules are there to allow forwarding. 

You are essentially needing to use wireguard as if it is installed on the host itself, which may actually be easier than using docker in this case!

**Comment by tvories** [comment]
Thanks for the insight.  I was trying to avoid having a special server just for my vpn, but I have thought more than once in this process that it may be easier that way.

That being said, I wouldn't mind trying to figure this out if it's possible.  I understand using the `--network host` mode, but I am such a noob when it comes to iptables that I am not sure how to set it up to forward it properly.

Do you have any suggestions for the proper commands to set up iptables to forward properly from the host to the container?

**Comment by htilly** [comment]
@tvories I might have the same setup as you.
I made a fork and did some changes. 
https://github.com/htilly/wireguard-docker

You need to supply the environment LOCAL_NETWORK to the config for this to work.

Was that what you were looking for ?

**Comment by tvories** [comment]
@htilly i have not had a chance to try that out yet, but I am going to give it a shot.  I will close this ticket in the meantime.

**Comment by BobWs** [comment]
Did you manage to get this to work? I’m looking for something similar. In my case I’m when the wg client is connected to the wg docker vpn I can connect to my local network via the local IP addresses but I would also like to do that via sub domains and that isn’t working now.
