### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by CasperNielsen** [cmulk/wireguard-docker#11]
Trying to install the docker image from a Hetzner cloud instance.
Getting this error when running the first "First Run"

> The following packages have unmet dependencies:
>  linux-headers-cloud-amd64 : Depends: linux-headers-5.4.0-4-cloud-amd64 (= 5.4.19-1) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

**Comment by cmulk** [comment]
I'm seeing this issue now too, not sure what changed, I'll need to troubleshoot more. thanks for bringing it up!

**Comment by cmulk** [comment]
looks like I need to do some smarter logic to detect the host kernel version in the initial install script, I will work on this when I can!
