### ISSUE TITLE
Only supports cloud debian variants

### ISSUE THREAD

**Issue by Fmstrat** [cmulk/wireguard-docker#12]
- Enhance to support non-cloud debian variants
- Add ubuntu bionic support

(PR coming shortly with new bionic branch)

**Comment by Fmstrat** [comment]
buster: https://github.com/cmulk/wireguard-docker/pull/13

stretch: https://github.com/cmulk/wireguard-docker/pull/14

For Ubuntu Bionic (18.04 LTS) I cannot create a new branch here to merge into. If you could create a `bionic` branch based off `buster`, I will merge: https://github.com/Fmstrat/wireguard-docker/tree/bionic

**Comment by cmulk** [comment]
This should already support non-cloud versions of debian (buster/stretch) amd64. I have installed on local debian instances for testing. As for ubuntu hosts, I will create a new branch, that's a good idea

**Comment by cmulk** [comment]
I think your issues related to using non-cloud debian versions may be related to #11 . I need to do some smarter host kernel detection in the install script (similar to what you have in your pull requests). I'll work on this when I can!

**Comment by cmulk** [comment]
install-modules on non-cloud variants should be fixed now with e70ec35
Will take a look at ubuntu support separately
