### ISSUE TITLE
docker build -t wireguard:local github.com/cmulk/wireguard-docker ERROR

### ISSUE THREAD

**Issue by Meesmaalt** [cmulk/wireguard-docker#2]
System: Debian 10 buster 64bit

Running this command:
docker build -t wireguard:local github.com/cmulk/wireguard-docker

Generates this issue:
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: fatal: Couldn't find remote ref master
: exit status 128

And i think this issue is a result of the above:

Running this command:
docker run --cap-add net_admin --cap-add sys_module -v wireguard_conf:/etc/wireguard -p 5555:5555/udp cmulk/wireguard-docker:buster

Results in this issue:
Wed Sep 11 08:54:33 UTC 2019: Interface not found in /etc/wireguard

**Comment by cmulk** [comment]
Oh I see, I do need to update the build command to use the new branches.
However the second error is unrelated I think as it is using the docket hub
image that is already built (no local build necessary). Looks like you
missed the install-module part, which is why the wireguard interface isn't
created

**Comment by Meesmaalt** [comment]
Thanks for taking a look. Any rough estimate when the fix would be done?

**Comment by Meesmaalt** [comment]
It built okay now but when i do this command:
`docker run --cap-add net_admin --cap-add sys_module -v wireguard_conf:/etc/wireguard -p 5555:5555/udp cmulk/wireguard-docker:buster`
Then it outputs:
`Tue Sep 17 17:58:58 UTC 2019: Interface not found in /etc/wireguard`
Building did generate a docker-compose.yml to /etc/wireguard.

**Comment by cmulk** [comment]
Same error as last time, you have to do the first run instructions first to
install the wireguard kernel modules

**Comment by Meesmaalt** [comment]
I have and it does it all. Yet it keeps giving me same error.

**Comment by Meesmaalt** [comment]
Fixed it by changing the docker run command to this:
`docker run -it --rm --cap-add net_admin --cap-add sys_module -v /etc/wireguard:/etc/wireguard -v /lib/modules:/lib/modules -p 5555:5555/udp cmulk/wireguard-docker:buster`

**Comment by Meesmaalt** [comment]
Would you be willing to help me troubleshoot something. I can pay.
If so, please provide me with a method to contact you.

**Comment by cmulk** [comment]
Sorry I don't really have the availability to do that
