### ISSUE TITLE
Problem with docker

### ISSUE THREAD

**Issue by alessiofx** [cmulk/wireguard-docker#20]
root@5e5d64c2bbda:/scripts# wg-quick up server
[#] ip link add server type wireguard
RTNETLINK answers: Operation not supported
Unable to access interface: Protocol not supported
[#] ip link delete dev server
Cannot find device "server"

**Comment by cmulk** [comment]
This is likely due to not having wireguard modules installed in your **host's** kernel.

There are 2 options:
1. Use a host that already has wireguard integrated in the kernel (Kernel >=5.6 or Ubuntu with kernel >=5.4)
2. Use a debian stretch or debian buster host and the install-module feature of this project

**Comment by alessiofx** [comment]
if i use the dokerfile i have the above problem.
if I use your image from the repository it works.
why?

**Comment by alessiofx** [comment]
> This is likely due to not having wireguard modules installed in your **host's** kernel.
> 
> There are 2 options:
> 
> 1. Use a host that already has wireguard integrated in the kernel (Kernel >=5.6 or Ubuntu with kernel >=5.4)
> 2. Use a debian stretch or debian buster host and the install-module feature of this project

I use host:
cat /etc/debian_version
10.5

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

lsb_release -da
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster


Kernel: Linux 4.19.0-10-amd64

**Comment by cmulk** [comment]
What does your dockerfile look like, the one that you said is not working? Once you do the install-module function once (maybe using the prebuilt image) you should be able to use a custom dockerfile for running wireguard after that. Also make sure you are running with `--cap-add net_admin --cap-add sys_module`

**Comment by alessiofx** [comment]
problem solved !

Disable secure boot on bios

**Comment by arinc9** [comment]
> What does your dockerfile look like, the one that you said is not working? Once you do the install-module function once (maybe using the prebuilt image) you should be able to use a custom dockerfile for running wireguard after that. Also make sure you are running with `--cap-add net_admin --cap-add sys_module`

Quick question, if I were to run multiple containers using the kernel module of the host, would it have everyone write to the same socket? If so, would that cause any unstability?

**Comment by cmulk** [comment]
I have not tried that so I can't say for sure. However, even though there are multiple containers using the kernel module for wireguard functions, it would be running separate network interfaces for each container so I think you should be fine.
