### ISSUE TITLE
Missing ip6tables-restore in alpine image

### ISSUE THREAD

**Issue by victornoel** [cmulk/wireguard-docker#21]
Hi,

I seems the alpine image is missing the binary `ip6tables-restore`:
```
vpn_1      | [#] ip6tables-restore -n
vpn_1      | /usr/bin/wg-quick: line 32: ip6tables-restore: command not found
```

Also, I had to explictly enable ipv6 on the alpine image too with the following setting in the docker-compose config:
```
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
```

**Comment by cmulk** [comment]
I haven't done any ip6 work with this, but I can add it to the alpine image for you. Just committed the change

**Comment by victornoel** [comment]
@cmulk thx :)
