### ISSUE TITLE
Unable to locate package linux-headers-4.19.128-microsoft-standard

### ISSUE THREAD

**Issue by marciomvm** [cmulk/wireguard-docker#25]
C:\WINDOWS\system32>docker run -it --rm --cap-add sys_module -v /lib/modules:/lib/modules cmulk/wireguard-docker:buster install-module

Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Hit:2 http://deb.debian.org/debian buster InRelease
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://deb.debian.org/debian buster-backports InRelease [46.7 kB]
Fetched 164 kB in 1s (302 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-headers-4.19.128-microsoft-standard
E: Couldn't find any package by glob 'linux-headers-4.19.128-microsoft-standard'
E: Couldn't find any package by regex 'linux-headers-4.19.128-microsoft-standard'
Unable to find kernel headers for running kernel: 4.19.128-microsoft-standard
Wireguard kernel module install failed.

any idea?

**Comment by cmulk** [comment]
The install-module command will only work if the host OS is the same as the container OS, so definitely won't be able to do this on WSL. However, if there is a way to install the wireguard module directly on WSL (I'm not sure if there is or not) , you should be able to use the "normal" run mode of this image.
