### ISSUE TITLE
Incorrect container platform

### ISSUE THREAD

**Issue by lachlancresswell** [cmulk/wireguard-docker#27]
Attempting to install today on a Pi4 with Buster and I'm getting:
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested`

Architecture on docker hub is also listed as AMD64.

**Comment by cmulk** [comment]
I have not tried any mulit-arch builds of this image (which is why it is only amd64) but I think it should theoretically be possible. Maybe you could try cloning this repo and building the image directly on your Pi
