### ISSUE TITLE
Unable to find linux-headers

### ISSUE THREAD

**Issue by LockedThread** [cmulk/wireguard-docker#28]
I have attempted to install wireguard using your exact process described in the README on Centos 7 & 8, Ubuntu 20.04, and Fedora 33. All of the problems stem from your "first-run" script which installs the linux-headers package.

Error on Ubuntu 20.04:
`Unable to locate package linux-headers-5.8.0-29-generic`

**Comment by cmulk** [comment]
The first run script is for installing the kernel module on the host system. For this reason, it only works on a debian buster or stretch host (the host has to be the same as the container to use this). The good news is that Ubuntu 20.04 already includes wireguard in the kernel so there is no need for the first run script. Not sure about Fedor and Centos, but if their kernels are later than 5.6 this should work as well (just skip the First Run part)
