### ISSUE TITLE
masquerade rule question

### ISSUE THREAD

**Issue by ghost** [cmulk/wireguard-docker#4]
For my use case, I do not require the `iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE` NAT rule applied in the run script.

I am applying my own iptables rules in the server configuration. Maybe a run env variable could be added to prevent the rule from being created?

**Comment by cmulk** [comment]
Sure makes sense! I will add that in sometime soon

**Comment by cmulk** [comment]
Done in 5667c49c376f4fdfb4b8a4c838dfaba872fc34a6 with the IPTABLES_MASQ environment variable. Set it to 0 to disable masquerading
