### ISSUE TITLE
/usr/bin/wg-quick: line 31: sysctl: command not found

### ISSUE THREAD

**Issue by brodybuster** [cmulk/wireguard-docker#5]
Using Debian Buster … I compiled the kernel module, that worked perfectly.
I can use this docker as a server, meaning I can use my server wg0.conf file and connect to it no problem. 

However, when I try to use this docker to connect to my Torguard VPN, I have two problems:
Sample client conf:

# TorGuard WireGuard Config
[Interface]
PrivateKey = <removed>
ListenPort = 51820
DNS = 1.1.1.1
Address = a.b.c.d

[Peer]
PublicKey = <removed>
AllowedIPs = 0.0.0.0/0
Endpoint = a.b.c.d
PersistentKeepalive = 25

First issue is that if I leave the DNS info in the conf file I receive this error
/usr/bin/wg-quick: line 31: resolvconf: command not found

I can comment out the DNS info and then instead of the resolv error I get this error
/usr/bin/wg-quick: line 31: sysctl: command not found

Either way the interface does not come  up in the container. Any ideas? Thanks

**Comment by brodybuster** [comment]
I'm half way there … I cloned the repo and updated the dockerfile to include procps

apt install -y --no-install-recommends procps wireguard-tools iptables nano net-tools && 

I also had update the docker compose to include "privileged: true":

version: '3'
services:
 vpn:
  container_name: wireguard
  image: <my built image name>
  volumes:
   - /opt/appdata/wireguard/config:/etc/wireguard
  networks:
   - net
  ports:
   - 5555:5555/udp
  restart: always
  cap_add:
   - NET_ADMIN
   - SYS_MODULE
   - SYS_ADMIN
  **privileged: true**
networks:
  net:

now it's working, minus the resolvconf issue.

**Comment by cmulk** [comment]
I've not tried to use this as the client before but that makes sense, I'll play around with it some more. Not sure why it would required the privileged flag in this setup.

As for resolvconf, you should just be able to install that package in the container as well, that's what wireguard uses to set the DNS info.

You probably also want to disable the outbound NAT masquerading with the IPTABLES_MASQ=0 environment variable

**Comment by brodybuster** [comment]
Foremost, thanks for the repIy.

I've been tweaking this a little more today. The privileged flag is need so that sysctl can mod the kernel parameters, which is something that wg-quick does behind the scenes when it brings up wg0 as a client. 

I'll tackle the resolv.conf issue next. My workaround for now is to disable it in the wg0.conf file. Then I modified your run file to have it create a new resolv.conf when the container gets created. I also added some IPTABLE rules in the run script as a kill switch in case wg0 goes down, which allows only VPN and LAN traffic through this container.  

I'll disable the masquerading per your advice. 

Thanks for your feedback

**Comment by cmulk** [comment]
Added the resolvconf and procps packages to the image, this should fix the DNS and "sysctl not found" issues.

Also it looks like the sysctl call is made only when you use a default route "0.0.0.0/0" in your client. This is also when it requires the container to run privileged (since its making the sysctl call)

**Comment by brodybuster** [comment]
That worked perfectly. Thanks. Maybe update the ReadMe to add that privileged is needed to use this as a client?

Not sure if you're interested in adding some functionality that will all allow you to chose whether the container is going to be used as a client or server? I run both. The server container to allow me to connect to my LAN from outside. The client container to connect to my VPN provider and stick some services behind it. So I spin up two containers from this image. Each container has its own compose file and conf file (obviously). Also each container functions slightly differently from the other. 

As you pointed out, if I am running this as a client. I turn of MASQ. I also add a kill switch when I am running as a client to make sure that nothing leaks past the VPN. 

So what I've done is something like this:

In the dockerfile, added an ENV variable to state whether its a client or server container, right below ENV IPTABLES_MASQ=1
https://pastebin.com/Q5nf1Hh9

Then modified to run script to add if, elif, else statement that will either 1) set the MASQ 2) add the kill swith or 3) bring wg0 back down because the container was not defined with SERVER/CLIENT. 
https://pastebin.com/cM6ZHs1y

**Comment by cmulk** [comment]
I like your idea except I wouldn't want to include the kill switch part directly in this image (unless you made it optional I guess) because there could be a case where users want to have a split tunnel on purpose. 
I'll definitely add a note to the README!
