### ISSUE TITLE
interface not found

### ISSUE THREAD

**Issue by ecsuae** [cmulk/wireguard-docker#7]
Hi ,I am following your instructions ,first I ran 
docker run -it --rm --cap-add sys_module -v /lib/modules:/lib/modules cmulk/wireguard-docker:buster install-module
and after that when I run this command I get error, can you help please
docker run --cap-add net_admin --cap-add sys_module -v wireguard_conf:/etc/wireguard -p 5555:5555/udp cmulk/wireguard-docker:buster
Sat Feb 22 22:46:35 UTC 2020: Interface not found in /etc/wireguard

**Comment by cmulk** [comment]
That sounds like maybe you haven't created an interface config yet? There is an example in the README or more explanation on the wiregaurd homepage (https://www.wireguard.com/)

**Comment by TUISTERa** [comment]
I guess that an example of interface.conf would be good in the repo

**Comment by cmulk** [comment]
The interface configs I'm thinking of have examples in the Configuration section of the README. You would name it wg0.conf as an example

**Comment by blackfan23** [comment]
@ecsuae 
In the command you posted try changing 

> wireguard_conf

to /etc/wireguard

`docker run --cap-add net_admin --cap-add sys_module -v /etc/wireguard:/etc/wireguard -p 5555:5555/udp cmulk/wireguard-docker:buster`

This works if a valid config is in /etc/wireguard on the host system. eg wg0.conf
